name: GitHub Settings Sync
description: GitHubの設定を同期するGitHub Actionsです。
author: finphie
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  repositories:
    description: カンマ・半角スペース・改行区切りにした「オーナー名/リポジトリ名」形式のリスト。オーナー名を省略した場合は、「GITHUB_REPOSITORY_OWNER」環境変数を使用。
    required: true
  has-issues:
    description: Issuesを有効にするかどうか。
    required: false
    default: true
  has-projects:
    description: Projectsを有効にするかどうか。
    required: false
    default: true
  has-wiki:
    description: Wikiを有効にするかどうか。
    required: false
    default: true
  allow-merge-commit:
    description: 「Create a merge commit」を有効にするか。
    required: false
    default: true
  allow-rebase-merge:
    description: 「Rebase and Merge」を有効にするか。
    required: false
    default: true
  allow-squash-merge:
    description: 「Squash Merge」を有効にするかどうか。
    required: false
    default: true
  allow-auto-merge:
    description: 自動マージ機能を有効にするか。
    required: false
    default: false
  delete-branch-on-merge:
    description: プルリクエストマージ時に、ブランチを自動的に削除するかどうか。
    required: false
    default: false
  allow-update-branch:
    description: 「Update branch」を有効にするかどうか。
    required: false
    default: false
  branch-protection:
    description: '[ブランチ保護]ブランチ保護を有効にするかどうか。'
    required: false
    default: false
  branch-protection-name:
    description: '[ブランチ保護]ブランチ名。'
    required: false
    default: main
  branch-protection-enforce-admins:
    description: '[ブランチ保護]管理者にも適用するか。'
    required: false
    default: false
  branch-protection-required-linear-history:
    description: '[ブランチ保護]直線状の履歴を必須にするかどうか。'
    required: false
    default: false
  branch-protection-allow-force-pushes:
    description: '[ブランチ保護]強制プッシュを許可するかどうか。'
    required: false
    default: false
  branch-protection-allow-deletions:
    description: '[ブランチ保護]プッシュアクセス権を持つユーザーが、保護されたブランチを削除できるようにするかどうか。'
    required: false
    default: false
  branch-protection-required-conversation-resolution:
    description: '[ブランチ保護]マージ前にコメントの解決を必須にするかどうか。'
    required: false
    default: false
  branch-protection-required-reviews:
    description: '[ブランチ保護][レビュー]レビューを必須にするかどうか。'
    required: false
    default: false
  branch-protection-required-reviews-dismiss-stale-reviews:
    description: '[ブランチ保護][レビュー]新しいコミットがプッシュされたときに、承認済みのレビューを却下するかどうか。'
    required: false
    default: false
  branch-protection-required-reviews-require-code-owner-review:
    description: '[ブランチ保護][レビュー]コード所有者のレビューが必須かどうか。'
    required: false
    default: false
  branch-protection-required-reviews-required-approving-review-count:
    description: '[ブランチ保護][レビュー]プルリクエストの承認に必要なレビュアーの数。'
    required: false
    default: 1

runs:
  using: docker
  image: 'docker://ghcr.io/finphie/git-hub-settings-sync:v0.2.1'
  args:
    - '--repositories'
    - "${{ inputs.repositories }}"

    - '--has-issues'
    - ${{ inputs.has-issues }}

    - '--has-projects'
    - ${{ inputs.has-projects }}

    - '--has-wiki'
    - ${{ inputs.has-wiki }}

    - '--allow-merge-commit'
    - ${{ inputs.allow-merge-commit }}

    - '--allow-rebase-merge'
    - ${{ inputs.allow-rebase-merge }}

    - '--allow-squash-merge'
    - ${{ inputs.allow-squash-merge }}

    - '--allow-auto-merge'
    - ${{ inputs.allow-auto-merge }}

    - '--delete-branch-on-merge'
    - ${{ inputs.delete-branch-on-merge }}

    - '--allow-update-branch'
    - ${{ inputs.allow-update-branch }}

    - '--branch-protection'
    - ${{ inputs.branch-protection }}

    - '--branch-protection-name'
    - ${{ inputs.branch-protection-name }}

    - '--branch-protection-enforce-admins'
    - ${{ inputs.branch-protection-enforce-admins }}

    - '--branch-protection-required-linear-history'
    - ${{ inputs.branch-protection-required-linear-history }}

    - '--branch-protection-allow-force-pushes'
    - ${{ inputs.branch-protection-allow-force-pushes }}

    - '--branch-protection-allow-deletions'
    - ${{ inputs.branch-protection-allow-deletions }}

    - '--branch-protection-required-conversation-resolution'
    - ${{ inputs.branch-protection-required-conversation-resolution }}

    - '--branch-protection-required-reviews'
    - ${{ inputs.branch-protection-required-reviews }}

    - '--branch-protection-required-reviews-dismiss-stale-reviews'
    - ${{ inputs.branch-protection-required-reviews-dismiss-stale-reviews }}

    - '--branch-protection-required-reviews-require-code-owner-review'
    - ${{ inputs.branch-protection-required-reviews-require-code-owner-review }}

    - '--branch-protection-required-reviews-required-approving-review-count'
    - ${{ inputs.branch-protection-required-reviews-required-approving-review-count }}
