name: GitHub Settings Sync
description: GitHubの設定を同期するGitHub Actionsです。
author: finphie
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  repositories:
    description: カンマ・半角スペース・改行区切りにした「オーナー名/リポジトリ名」形式のリスト。オーナー名を省略した場合は、「GITHUB_REPOSITORY_OWNER」環境変数を使用。
    required: true
    type: string
  has-issues:
    description: Issuesを有効にするかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  has-projects:
    description: Projectsを有効にするかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  has-wiki:
    description: Wikiを有効にするかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  has-discussions:
    description: Discussionsを有効にするかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
  allow-merge-commit:
    description: 「Create a merge commit」を有効にするか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  allow-squash-merge:
    description: 「Squash Merge」を有効にするかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  allow-rebase-merge:
    description: 「Rebase and Merge」を有効にするか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  allow-auto-merge:
    description: 自動マージ機能を有効にするか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  delete-branch-on-merge:
    description: プルリクエストマージ時に、ブランチを自動的に削除するかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  allow-update-branch:
    description: 「Update branch」を有効にするかどうか。
    required: false
    type: choice
    options:
      - Unchanged
      - true
      - false
    default: Unchanged
  merge-commit-title:
    description: マージにおけるコミットタイトルの種類。
    required: false
    type: choice
    options:
      - Unchanged
      - PullRequestTitle
      - MergeMessage
    default: Unchanged
  merge-commit-message:
    description: マージにおけるコミットメッセージの種類。
    required: false
    type: choice
    options:
      - Unchanged
      - PullRequestTitle
      - PullRequestBody
      - Blank
    default: Unchanged
  squash-merge-commit-title:
    description: スカッシュマージにおけるコミットタイトルの種類。
    required: false
    type: choice
    options:
      - Unchanged
      - PullRequestTitle
      - CommitOrPullRequestTitle
    default: Unchanged
  squash-merge-commit-message:
    description: スカッシュマージにおけるコミットメッセージの種類。
    required: false
    type: choice
    options:
      - Unchanged
      - PullRequestBody
      - CommitMessages
      - Blank
    default: Unchanged
  branch-protection:
    description: '[ブランチ保護]ブランチ保護を有効にするかどうか。'
    required: false
    default: false
  branch-protection-name:
    description: '[ブランチ保護]ブランチ名。'
    required: false
    type: string
    default: main
  branch-protection-enforce-admins:
    description: '[ブランチ保護]管理者にも適用するか。'
    required: false
    type: boolean
    default: false
  branch-protection-required-linear-history:
    description: '[ブランチ保護]直線状の履歴を必須にするかどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-allow-force-pushes:
    description: '[ブランチ保護]強制プッシュを許可するかどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-allow-deletions:
    description: '[ブランチ保護]プッシュアクセス権を持つユーザーが、保護されたブランチを削除できるようにするかどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-required-conversation-resolution:
    description: '[ブランチ保護]マージ前にコメントの解決を必須にするかどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-required-reviews:
    description: '[ブランチ保護][レビュー]レビューを必須にするかどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-required-reviews-dismiss-stale-reviews:
    description: '[ブランチ保護][レビュー]新しいコミットがプッシュされたときに、承認済みのレビューを却下するかどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-required-reviews-require-code-owner-reviews:
    description: '[ブランチ保護][レビュー]コード所有者のレビューが必須かどうか。'
    required: false
    type: boolean
    default: false
  branch-protection-required-reviews-required-approving-review-count:
    description: '[ブランチ保護][レビュー]プルリクエストの承認に必要なレビュアーの数。'
    required: false
    type: number
    default: 1

runs:
  using: docker
  image: 'docker://ghcr.io/finphie/git-hub-settings-sync:v1.1.0'
  args:
    - '--repositories'
    - '${{ inputs.repositories }}'

    - '--has-issues'
    - ${{ inputs.has-issues }}

    - '--has-projects'
    - ${{ inputs.has-projects }}

    - '--has-wiki'
    - ${{ inputs.has-wiki }}

    - '--has-discussions'
    - ${{ inputs.has-discussions }}

    - '--allow-merge-commit'
    - ${{ inputs.allow-merge-commit }}

    - '--allow-rebase-merge'
    - ${{ inputs.allow-rebase-merge }}

    - '--allow-squash-merge'
    - ${{ inputs.allow-squash-merge }}

    - '--allow-auto-merge'
    - ${{ inputs.allow-auto-merge }}

    - '--delete-branch-on-merge'
    - ${{ inputs.delete-branch-on-merge }}

    - '--allow-update-branch'
    - ${{ inputs.allow-update-branch }}

    - '--merge-commit-title'
    - ${{ inputs.merge-commit-title }}

    - '--merge-commit-message'
    - ${{ inputs.merge-commit-message }}

    - '--squash-merge-commit-title'
    - ${{ inputs.squash-merge-commit-title }}

    - '--squash-merge-commit-message'
    - ${{ inputs.squash-merge-commit-message }}

    - '--branch-protection'
    - ${{ inputs.branch-protection }}

    - '--branch-protection-name'
    - ${{ inputs.branch-protection-name }}

    - '--branch-protection-enforce-admins'
    - ${{ inputs.branch-protection-enforce-admins }}

    - '--branch-protection-required-linear-history'
    - ${{ inputs.branch-protection-required-linear-history }}

    - '--branch-protection-allow-force-pushes'
    - ${{ inputs.branch-protection-allow-force-pushes }}

    - '--branch-protection-allow-deletions'
    - ${{ inputs.branch-protection-allow-deletions }}

    - '--branch-protection-required-conversation-resolution'
    - ${{ inputs.branch-protection-required-conversation-resolution }}

    - '--branch-protection-required-reviews'
    - ${{ inputs.branch-protection-required-reviews }}

    - '--branch-protection-required-reviews-dismiss-stale-reviews'
    - ${{ inputs.branch-protection-required-reviews-dismiss-stale-reviews }}

    - '--branch-protection-required-reviews-require-code-owner-reviews'
    - ${{ inputs.branch-protection-required-reviews-require-code-owner-reviews }}

    - '--branch-protection-required-reviews-required-approving-review-count'
    - ${{ inputs.branch-protection-required-reviews-required-approving-review-count }}
