name: GitHub Settings Sync
description: This is an application to synchronize GitHub settings.
author: finphie
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  repository:
    description: \"owner/repo\" format repository name.
    required: true
  path:
    description: File path of the configuration file.
    required: true

runs:
  using: docker
  image: 'docker://ghcr.io/finphie/git-hub-settings-sync:v3.0.0'
  args:
    - '--repository'
    - '${{ inputs.repository }}'

    - '--path'
    - ${{ inputs.path }}
