name: Deploy

on:
  pull_request:

jobs:
  docker-dotnet:
    name: Docker(.NET)
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:v0.01
