name: Test

on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  check:
    name: Check
    uses: finphie/Actions/.github/workflows/get-version.yml@main

  main:
    name: test
    needs: check
    runs-on: ubuntu-latest

    steps:
      - shell: pwsh
        run: |
          echo '${{ needs.check.outputs.version }}'
          echo '${{ needs.check.outputs.version-major }}'
          echo '${{ needs.check.outputs.release }}'
          echo '${{ needs.check.outputs.dotnet }}'
          echo '${{ needs.check.outputs.docker }}'
